# Generated by Django 5.2.7 on 2026-08-26 08:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_review_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Full-width background image for hero_brand slides. If set, displayed behind the text instead of the gradient.', max_length=255, null=True, verbose_name='background_image'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='slide_type',
            field=models.CharField(choices=[('vendor_promo', 'Vendor Promo (Desktop Side Banner)'), ('hero_brand', 'Hero Brand Slide (Mobile)')], default='vendor_promo', help_text='Determines where this slide is rendered.', max_length=20),
        ),
    ]
