# Generated by Django 5.2.7 on 2026-08-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_add_promotion_background_image_and_slide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='frequency_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours before this popup shows again to the same visitor after they dismiss it. Only applies to event_popup type.'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank to start immediately', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='slide_type',
            field=models.CharField(choices=[('vendor_promo', 'Vendor Promo (Desktop Side Banner)'), ('hero_brand', 'Hero Brand Slide (Mobile)'), ('event_popup', 'Event/Campaign Popup')], default='vendor_promo', help_text='Determines where this slide is rendered.', max_length=20),
        ),
    ]
