# Generated by Django 5.2.7 on 2026-08-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_promotion_end_date_promotion_frequency_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='hero_slot',
            field=models.CharField(blank=True, choices=[('campus_essentials', 'Campus Essentials'), ('tech_electronics', 'Tech & Electronics'), ('fashion_accessories', 'Fashion & Accessories'), ('food_beverages', 'Food & Beverages'), ('deals_marketplace', 'Deals & Marketplace')], help_text='Which fixed hero slot this record overrides. Only used when slide_type=hero_brand.', max_length=30, null=True),
        ),
    ]
