# Generated by Django 5.2.7 on 2026-08-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_add_hero_slot_to_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='frequency_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='Minutes before this popup shows again after being dismissed. E.g. 10 for 10 minutes, 1440 for 24 hours.'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='frequency_hours',
            field=models.PositiveIntegerField(default=24, help_text='Deprecated — use frequency_minutes. Kept temporarily for data migration.'),
        ),
    ]
