# Generated by Django 5.2.7 on 2026-08-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_populate_frequency_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='frequency_hours',
        ),
    ]
