# Generated by Django 5.2.7 on 2026-08-29 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_frequency_hours'),
        ('vendors', '0023_add_product_sponsorship_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='hero_slot',
            field=models.CharField(blank=True, choices=[('campus_essentials', 'Campus Essentials'), ('tech_electronics', 'Tech & Electronics'), ('fashion_accessories', 'Fashion & Accessories'), ('food_beverages', 'Food & Beverages'), ('deals_marketplace', 'Deals & Marketplace'), ('top_seller', 'Top Seller This Week')], help_text='Which fixed hero slot this record overrides. Only used when slide_type=hero_brand.', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('counterfeit', 'Counterfeit / fake item'), ('prohibited', 'Prohibited or illegal item'), ('misleading', 'Misleading listing or description'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Optional additional context from the reporter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Under Review'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vendors.product')),
                ('reporter', models.ForeignKey(blank=True, help_text='Blank if report was submitted anonymously', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_product_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Report',
                'verbose_name_plural': 'Product Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
