# Generated by Django 5.2.7 on 2026-08-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_promotion_hero_slot_productreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreport',
            name='reporter_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the reporter, used for rate-limiting anonymous reports', null=True),
        ),
    ]
