# Generated by Django 5.2.7 on 2026-09-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_productreport_reporter_ip'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='wallettransaction',
                    name='wallet',
                ),
                migrations.AlterUniqueTogether(
                    name='wallettransaction',
                    unique_together=None,
                ),
                migrations.DeleteModel(name='Dispute'),
                migrations.DeleteModel(name='MainOrder'),
                migrations.DeleteModel(name='PaymentTransaction'),
                migrations.DeleteModel(name='RefundRecord'),
                migrations.DeleteModel(name='SubOrder'),
                migrations.DeleteModel(name='SubOrderItem'),
                migrations.DeleteModel(name='WalletTransaction'),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS marketplace_wallettransaction;"),
                migrations.RunSQL("DROP TABLE IF EXISTS marketplace_dispute;"),
                migrations.RunSQL("DROP TABLE IF EXISTS marketplace_refundrecord;"),
                migrations.RunSQL("DROP TABLE IF EXISTS marketplace_suborderitem;"),
                migrations.RunSQL("DROP TABLE IF EXISTS marketplace_suborder;"),
                migrations.RunSQL("DROP TABLE IF EXISTS marketplace_mainorder;"),
                migrations.RunSQL("DROP TABLE IF EXISTS marketplace_paymenttransaction;"),
            ],
        ),
    ]
