# Generated by Django 5.2.7 on 2026-09-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_remove_cart_add_wishlist_guest_support'),
        ('vendors', '0029_add_webhook_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='marketplace.review')),
            ],
            options={
                'verbose_name': 'Review Reply',
                'verbose_name_plural': 'Review Replies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', help_text='Set for anonymous (guest) clicks', max_length=40)),
                ('channel', models.CharField(choices=[('call', 'Phone Call'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_intents', to='vendors.product')),
                ('user', models.ForeignKey(blank=True, help_text='Set when user is authenticated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_intents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_intents', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Contact Intent',
                'verbose_name_plural': 'Contact Intents',
                'ordering': ['-contacted_at'],
                'indexes': [models.Index(fields=['vendor', 'contacted_at'], name='marketplace_vendor__e47552_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', help_text='Set for anonymous (guest) views', max_length=40)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='vendors.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='vendors.store')),
                ('user', models.ForeignKey(blank=True, help_text='Set when user is authenticated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'product'], name='marketplace_user_id_0bd853_idx'), models.Index(fields=['product', 'viewed_at'], name='marketplace_product_5567dd_idx')],
            },
        ),
    ]
