# Generated by Django 5.2.7 on 2026-09-07 21:25

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0025_remove_refundrequest_order_remove_transaction_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price (for showing discounts)', max_digits=10, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Category-specific attributes (key = SubCategoryAttribute ID, value = attribute value)')),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Listing expires exactly 10 days after creation')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quicksell_listings', to='vendors.subcategory')),
                ('user', models.ForeignKey(blank=True, help_text='Seller who created this listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quicksell_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Sell Listing',
                'verbose_name_plural': 'Quick Sell Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickSellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quicksell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quicksell.quicksell')),
            ],
            options={
                'verbose_name': 'Quick Sell Image',
                'verbose_name_plural': 'Quick Sell Images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickSellReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the reporter, used for rate-limiting anonymous reports', null=True)),
                ('reason', models.CharField(choices=[('counterfeit', 'Counterfeit / fake item'), ('prohibited', 'Prohibited or illegal item'), ('misleading', 'Misleading listing or description'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Optional additional context from the reporter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Under Review'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('quicksell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='quicksell.quicksell')),
                ('reporter', models.ForeignKey(blank=True, help_text='Blank if report was submitted anonymously', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quicksell_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quicksell_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Sell Report',
                'verbose_name_plural': 'Quick Sell Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quicksell',
            index=models.Index(fields=['user', 'created_at'], name='quicksell_q_user_id_d88336_idx'),
        ),
        migrations.AddIndex(
            model_name='quicksell',
            index=models.Index(fields=['subcategory', 'created_at'], name='quicksell_q_subcate_947ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='quicksell',
            index=models.Index(fields=['expires_at'], name='quicksell_q_expires_b48d88_idx'),
        ),
        migrations.AddIndex(
            model_name='quicksell',
            index=models.Index(fields=['slug'], name='quicksell_q_slug_56532c_idx'),
        ),
    ]
