# Generated by Django 5.2.7 on 2026-09-09 05:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicksell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksell',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional product video (max ~60s recommended)', max_length=255, null=True, verbose_name='video'),
        ),
    ]
