# Generated by Django 5.2.7 on 2026-03-04 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(help_text='Hashed OTP code', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When OTP was created (timezone-aware)')),
                ('expires_at', models.DateTimeField(help_text='When OTP expires (timezone-aware)')),
                ('is_used', models.BooleanField(default=False, help_text='Marks OTP as used (prevents reuse)')),
                ('used_at', models.DateTimeField(blank=True, help_text='When OTP was successfully used', null=True)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of verification attempts')),
                ('user', models.OneToOneField(help_text='User requesting OTP verification', on_delete=django.db.models.deletion.CASCADE, related_name='otp_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='users_otpve_user_id_421c8a_idx'), models.Index(fields=['expires_at'], name='users_otpve_expires_4f8a2d_idx')],
            },
        ),
    ]
