# Generated by Django 5.2.7 on 2026-03-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked after max verification attempts exceeded'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When OTP was locked due to max attempts', null=True),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'created_at'], name='users_otpve_user_id_ca18b4_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['is_locked'], name='users_otpve_is_lock_11d0f2_idx'),
        ),
    ]
