# Generated by Django 5.2.7 on 2026-08-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpverification_is_locked_otpverification_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_generation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of OTP generation requests in the current window'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_window_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current OTP generation rate-limit window started', null=True),
        ),
    ]
