# Generated by Django 5.2.7 on 2026-09-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_otp_generation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='default_address',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='state',
        ),
    ]
