# Generated by Django 5.2.7 on 2025-11-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific attributes (brand, size, specs, etc.)'),
        ),
        migrations.CreateModel(
            name='SubCategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Attribute name (e.g., 'Brand', 'Size', 'RAM')", max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='vendors.subcategory')),
            ],
        ),
    ]
