# Generated by Django 5.2.7 on 2025-11-26 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_product_attributes_subcategoryattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoryattribute',
            options={'ordering': ['subcategory', 'sort_order', 'name'], 'verbose_name': 'SubCategory Attribute', 'verbose_name_plural': 'SubCategory Attributes'},
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('dropdown', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('textarea', 'Text Area'), ('radio', 'Radio Buttons')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='help_text',
            field=models.CharField(blank=True, help_text='Help text shown to vendor', max_length=300),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='Max value for number fields', null=True),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Min value for number fields', null=True),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text="Dropdown/radio options as list (e.g., ['New', 'Used', 'Refurbished'])"),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text', max_length=200),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategoryattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoryattribute',
            unique_together={('subcategory', 'name')},
        ),
    ]
