# Generated by Django 5.2.7 on 2026-01-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_subcategoryattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this number'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='Enable stock tracking for this product'),
        ),
    ]
