# Generated by Django 5.2.7 on 2026-01-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_remove_product_quantity_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='track_inventory',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('discontinued', 'Discontinued')], default='draft', max_length=20),
        ),
    ]
