# Generated by Django 5.2.7 on 2026-01-18 02:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_add_profile_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='main_category_change_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times main category has been changed'),
        ),
        migrations.AddField(
            model_name='store',
            name='main_category_last_changed_at',
            field=models.DateTimeField(blank=True, help_text='Last time main category was changed (via admin approval)', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='original_main_category',
            field=models.ForeignKey(blank=True, help_text='Original main category for tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_stores', to='vendors.maincategory'),
        ),
        migrations.AddField(
            model_name='store',
            name='original_store_name',
            field=models.CharField(blank=True, help_text='Original store name for tracking', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_change_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times store name has been changed'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_last_changed_at',
            field=models.DateTimeField(blank=True, help_text='Last time store name was changed', null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='admin_internal_notes',
            field=models.TextField(blank=True, help_text='Private notes visible only to admins (not shown to vendor)'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bvn_full_name',
            field=models.CharField(blank=True, help_text='Full name from BVN verification (for comparison)', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='name_mismatch_details',
            field=models.CharField(blank=True, help_text="Details about name mismatch (e.g., 'NIN: John Doe vs BVN: John D. Doe')", max_length=500),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Automated risk assessment score (0-100, higher = riskier)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
