# Generated by Django 5.2.7 on 2026-02-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_store_main_category_change_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('payment', 'Payment Received'), ('refund', 'Refund Request'), ('verification', 'Verification Update'), ('admin_message', 'Admin Message'), ('system', 'System Message')], max_length=20),
        ),
    ]
