# Generated by Django 5.2.7 on 2026-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Store latitude (set by vendor in store settings)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Store longitude (set by vendor in store settings)', max_digits=9, null=True),
        ),
    ]
