# Generated by Django 5.2.7 on 2026-03-02 05:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_store_latitude_store_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Recommended: 1200x350px, max 8MB', max_length=255, null=True, verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Recommended: 400x400px, max 5MB', max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='photo_from_nin',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_from_nin'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='selfie',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='selfie'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='student_id_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_id_image'),
        ),
    ]
