# Generated by Django 5.2.7 on 2026-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_alter_productimage_image_alter_store_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, help_text='Paystack transfer recipient code', max_length=100),
        ),
    ]
