# Generated by Django 5.2.7 on 2026-06-25 09:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_wallet_paystack_recipient_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='bvn_full_name',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='duplicate_nin_vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='has_duplicate_nin',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='has_name_mismatch',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='identity_status',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='name_mismatch_details',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='nin_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='nin_verification_ip',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='nin_verified_at',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='photo_from_nin',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='identity_selfie',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Live selfie captured during BVN identity verification. Separate from `selfie` (student verification photo) — never overwrite that field.', max_length=255, null=True, verbose_name='identity_selfie'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='selfie_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Dojah confidence_value, 0-100. Drives the 3-tier verification outcome.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='selfie_image_url',
            field=models.URLField(blank=True, help_text='Dojah-hosted reference copy of the selfie (selfie_image_url from API response)'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='selfie_match',
            field=models.BooleanField(blank=True, help_text="Dojah's own match result (true/false, hardcoded 90% cutoff). Business logic uses selfie_confidence directly, not this field.", null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('verified', 'Verified'), ('pending_review', 'Pending Admin Review'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='calculated_age',
            field=models.PositiveIntegerField(blank=True, help_text="Vendor's age calculated from DOB at time of verification", null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='From BVN phone_number1. Admin-only — masked to vendor via get_masked_phone().', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='selfie',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Student verification selfie. NOT the same field as identity_selfie.', max_length=255, null=True, verbose_name='selfie'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('bvn_verified', 'BVN Verified'), ('student_verified', 'Student Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
