# Generated by Django 5.2.7 on 2026-07-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_remove_vendorprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReviewVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Verification Review',
                'verbose_name_plural': 'Pending Verification Reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vendors.vendorprofile',),
        ),
    ]
