# Generated by Django 5.2.7 on 2026-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_pendingreviewvendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationattempt',
            name='attempt_type',
            field=models.CharField(choices=[('bvn', 'BVN Verification'), ('student', 'Student Verification'), ('otp', 'OTP Verification')], max_length=20),
        ),
    ]
