# Generated by Django 5.2.7 on 2026-07-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_alter_verificationattempt_attempt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Manually promoted store — takes priority over auto-ranked top sellers'),
        ),
        migrations.AddField(
            model_name='store',
            name='sponsored_until',
            field=models.DateTimeField(blank=True, help_text='Optional expiry — sponsorship auto-drops after this date if set', null=True),
        ),
    ]
