# Generated by Django 5.2.7 on 2026-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_store_is_sponsored_store_sponsored_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.CharField(blank=True, default='package', help_text="Lucide icon name (for example: 'laptop', 'shirt', or 'package')", max_length=50),
        ),
    ]
