# Generated by Django 5.2.7 on 2026-08-21 22:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_maincategory_icon_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional product video (max ~60s recommended)', max_length=255, null=True, verbose_name='video'),
        ),
    ]
