# Generated by Django 5.2.7 on 2026-08-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_product_average_rating_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending_score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
