# Generated by Django 5.2.7 on 2026-08-23 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_add_trending_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='bvn_consent_given',
            field=models.BooleanField(default=False, help_text='Vendor consented to BVN collection and submission to Dojah for identity verification.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bvn_consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when BVN collection consent was given.', null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bvn_number',
            field=models.CharField(blank=True, help_text='Cleared after successful verification — never retained long-term.', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'BVN must be 11 digits')], verbose_name='BVN'),
        ),
    ]
