# Generated by Django 5.2.7 on 2026-08-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0022_clear_bvn_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sponsored_priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher priority shows first among sponsored products'),
        ),
        migrations.AddField(
            model_name='product',
            name='sponsored_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
