# Generated by Django 5.2.7 on 2026-09-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_add_product_sponsorship_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('discontinued', 'Discontinued'), ('removed', 'Removed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='End of the free trial period.', null=True)),
                ('period_end', models.DateTimeField(blank=True, help_text='When the current paid period expires.', null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, help_text='Grace period end — store stays visible until this date.', null=True)),
                ('paystack_customer_code', models.CharField(blank=True, default='', help_text='Paystack customer code for this vendor.', max_length=100)),
                ('paystack_subscription_code', models.CharField(blank=True, default='', help_text='Paystack subscription code.', max_length=100)),
                ('paystack_plan_code', models.CharField(blank=True, default='', help_text='Paystack plan code used for this subscription.', max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of consecutive payment retry attempts.')),
                ('last_payment_attempt_at', models.DateTimeField(blank=True, help_text='Timestamp of the last payment retry attempt.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
