# Generated by Django 5.2.7 on 2026-09-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_remove_mainorder_buyer_remove_suborder_main_order_and_more'),
        ('vendors', '0024_alter_product_status_subscription'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Order'),
                migrations.DeleteModel(name='OrderItem'),
                migrations.DeleteModel(name='RefundRequest'),
                migrations.DeleteModel(name='Transaction'),
                migrations.DeleteModel(name='Wallet'),
            ],
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS vendors_refundrequest;"),
                migrations.RunSQL("DROP TABLE IF EXISTS vendors_transaction;"),
                migrations.RunSQL("DROP TABLE IF EXISTS vendors_orderitem;"),
                migrations.RunSQL("DROP TABLE IF EXISTS vendors_order;"),
                migrations.RunSQL("DROP TABLE IF EXISTS vendors_wallet;"),
            ],
        ),
    ]
