# Generated by Django 5.2.7 on 2026-09-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_remove_refundrequest_order_remove_transaction_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, help_text='Area or city within the state', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, help_text='State or region', max_length=100),
        ),
    ]
