# Generated by Django 5.2.7 on 2026-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0028_backfill_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('payment', 'Payment Received'), ('refund', 'Refund Request'), ('verification', 'Verification Update'), ('admin_message', 'Admin Message'), ('system', 'System Message'), ('inventory', 'Inventory Alert'), ('wishlist', 'Wishlist Activity'), ('subscription', 'Subscription Update')], max_length=20),
        ),
    ]
