# Generated by Django 5.2.7 on 2026-09-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0029_add_webhook_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='total_orders',
        ),
    ]
