# Generated by Django 5.2.7 on 2026-09-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0030_remove_store_total_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='total_sales',
        ),
    ]
