# Generated by Django 5.2.7 on 2026-09-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0031_remove_store_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('verification', 'Verification Update'), ('admin_message', 'Admin Message'), ('system', 'System Message'), ('inventory', 'Inventory Alert'), ('wishlist', 'Wishlist Activity'), ('subscription', 'Subscription Update')], max_length=20),
        ),
    ]
