# Generated by Django 5.2.7 on 2026-09-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0032_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='If True, subscription will not auto-renew and will expire at period_end.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.CharField(blank=True, choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan')], default='', help_text='Plan the vendor will move to when the current paid period ends.', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan')], default='free', help_text='Current subscription tier.', max_length=10),
        ),
    ]
