# Generated by Django 5.2.7 on 2026-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0033_subscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='first_product_at',
            field=models.DateTimeField(blank=True, help_text='When the vendor created their first product (starts the 7-day countdown).', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='qualification_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('grace', 'Grace period'), ('qualified', 'Qualified'), ('failed', 'Failed'), ('skipped', 'Skipped (paid plan)')], default='not_started', help_text='Free-plan first-product qualification state.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='qualified_at',
            field=models.DateTimeField(blank=True, help_text='When the vendor passed qualification (3 published products).', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('qualifying', 'Qualifying (Free Plan)'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
    ]
