# Generated by Django 5.2.7 on 2026-10-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0034_subscription_first_product_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Notification kind, e.g. trial_ending_soon.', max_length=40)),
                ('cycle_key', models.CharField(help_text='Cycle identifier, usually an ISO date (YYYY-MM-DD).', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='vendors.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Notification Log',
                'verbose_name_plural': 'Subscription Notification Logs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'kind', 'cycle_key'), name='uniq_subscription_notification_cycle')],
            },
        ),
    ]
