# Generated by Django 5.2.7 on 2026-10-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0035_subscription_notification_dedupe_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='has_vbatch',
            field=models.BooleanField(default=False, help_text='Persistent V-Batch badge. Awarded once by code and never removed by code - only a manual admin edit changes it.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vbatch_earned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vbatch_source',
            field=models.CharField(blank=True, choices=[('bvn', 'BVN verification'), ('premium', 'Premium plan'), ('admin', 'Admin'), ('legacy', 'Legacy backfill')], default='', help_text='How the V-Batch was earned (bvn, premium, admin, legacy).', max_length=10),
        ),
    ]
