# Generated by Django 5.2.7 on 2026-10-02 22:36

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    """Seed the singleton row so the platform toggle starts OFF (default)."""
    PlatformSettings = apps.get_model('vendors', 'PlatformSettings')
    PlatformSettings.objects.get_or_create(pk=1)


def remove_default_settings(apps, schema_editor):
    """Reverse: the row is only removed together with its table."""
    PlatformSettings = apps.get_model('vendors', 'PlatformSettings')
    PlatformSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0036_add_vbatch_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn_verification_enabled', models.BooleanField(default=False, help_text='ON: vendors can run BVN verification and a BVN success earns the V-Batch. OFF: the BVN flow is rejected before any Dojah call and no V-Batch is awarded. Turning this off never removes an earned V-Batch or a completed verification.')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.RunPython(create_default_settings, remove_default_settings),
    ]
