# Generated by Django 5.2.7 on 2026-10-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0037_platformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pending_plan',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Plan'), ('premium', 'Premium Plan')], default='', help_text='Plan the vendor will move to when the current paid period ends.', max_length=10),
        ),
    ]
